# This workflows will update Python Package so it can be installed using pip

name: Continuous Deployment of Python Package

on:
  pull_request:
  push:
    branches: 
      - "master"

jobs:
  deploy:

    runs-on: ubuntu-latest

    # Install and setup Linux environment
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install setuptools wheel

    # Call custom python script to auto increment package version
    - name: Update packager version
      run: |
        python packageVersionUpdater.py
    - name: Clear old package
      run: |
        rm -r build
    - name: Build new package
      run: |
        python3 setup.py sdist bdist_wheel

    # Commit the rebuilt python package to the same branch
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply python package update
        branch: release/
